{
 "title": "Scout Plugin",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "content": "\n### Scout v0.1.0-alpha\n\n**Original Author:** YWJT http://www.ywjt.org/ (Copyright © 2019)  \n**Maintainer:** ZhiQiang Koo <350311204@qq.com> \n",
   "targets": [
    { "target": "select metric", "type": "timeseries" }
   ]
  },
  {
   "title": "运行时间",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    { "target": "uptime", "type": "timeseries" }
   ]
  },
  {
   "title": "执行列表",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "target": "active_table", "type": "table" }
   ]
  },
  {
   "title": "空闲内存",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 3 },
   "format": "kbytes",
   "valueName": "first",
   "targets": [
    { "target": "mem_free", "type": "timeseries" }
   ]
  },
  {
   "title": "CPU使用率(%)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 3, "y": 3 },
   "targets": [
    { "target": "cpu_percent", "type": "timeseries" }
   ]
  },
  {
   "title": "累计异常包",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 3 },
   "format": "none",
   "valueName": "total",
   "targets": [
    { "target": "excep_packet", "type": "timeseries" }
   ]
  },
  {
   "title": "当前负载",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 7 },
   "targets": [
    { "target": "loadavg", "type": "timeseries" }
   ]
  },
  {
   "title": "当前带宽",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 7 },
   "targets": [
    { "target": "netflow", "type": "timeseries" }
   ]
  },
  {
   "title": "Bolt TCP",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    { "target": "bolt_tcp", "type": "timeseries" }
   ]
  },
  {
   "title": "负载曲线",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "loadavg", "type": "timeseries" }
   ]
  },
  {
   "title": "Bolt UDP",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    { "target": "bolt_udp", "type": "timeseries" }
   ]
  },
  {
   "title": "流量曲线",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    { "target": "netflow", "type": "timeseries" }
   ]
  }
 ]
}